name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/pbharambe/my-image-name:latest
        docker push ghcr.io/pbharambe/my-image-name:latest
        docker pull ghcr.io/pbharambe/my-image-name:latest
        docker run ghcr.io/pbharambe/my-image-name:latest
        
